### ISSUE TITLE
Alerting Feature 

### ISSUE THREAD

**Issue by rish691** [hypertrace/hypertrace-alert-engine#41]
Uber ticket for Phase2 of alerting work.

Parent Issue:
https://github.com/hypertrace/hypertrace/issues/251

Phase 2: 
- [x] #52
- [ ] #53
- [ ] #54
- [ ] Internal metric data time series structure in MetricAnomalyDetector 
- [ ] #55
- [ ] Support evaluation of error percentage metrics

**Comment by kotharironak** [comment]
Closing this, refer parent ticket for phase status - Parent Issue:
hypertrace/hypertrace#251
