### ISSUE TITLE
Alerting not working in v1.0.8

### ISSUE THREAD

**Issue by sarthak77** [hypertrace/hypertrace-alert-engine#44]
Error in notifications for alerting in the latest version. 

Reference PR : https://github.com/hypertrace/hypertrace-alert-engine/pull/31 (problem)
Reference PR : https://github.com/hypertrace/hypertrace-alert-engine/pull/45 (solution)

**Comment by rish691** [comment]
nit: alerting-engine service itself isn't coming up in 1.0.8 version, so essentially nothing works
