### ISSUE TITLE
Expose api on gateway services for baseline

### ISSUE THREAD

**Issue by rish691** [hypertrace/hypertrace-alert-engine#54]
The idea is to query gateway for baseline calculation. So an api needs to be exposed on gateway service which accepts metric data as list and returns the default baseline, the api can enhanced to include other baseline functions if/when needed 

Baseline calculation code already exists in gateway service https://github.com/hypertrace/gateway-service/blob/main/gateway-service-impl/src/main/java/org/hypertrace/gateway/service/baseline/BaselineCalculator.java 
and it just needs to reused in the api implementation 

```
rpc calculateBaselineForMetricValues(double[] values) returns org.hypertrace.gateway.service.v1.baseline.Baseline {}
```

https://github.com/hypertrace/gateway-service/blob/main/gateway-service-api/src/main/proto/org/hypertrace/gateway/service/v1/baseline.proto

Changes needed in BaselineRuleEvaluator
https://github.com/hypertrace/hypertrace-alert-engine/blob/main/metric-anomaly-detector/src/main/java/org/hypertrace/alert/engine/metric/anomaly/detector/evaluator/BaselineRuleEvaluator.java#L128

**Comment by kotharironak** [comment]
Adding a comment link for now - https://github.com/hypertrace/hypertrace-alert-engine/pull/51/files#r688270413
will add details here.

**Comment by kotharironak** [comment]
@pavan-traceable Can you also review this?

**Comment by pavan-traceable** [comment]
> @pavan-traceable Can you also review this?

@kotharironak  review on pull request or approach ? Is it replacing baseline calculation from Median to other implementation ?

**Comment by rish691** [comment]
I think ronak is asking for a review on the api-spec and the approach itself. 
We are not changing the baseline calculation logic on gateway, just exposing it as an api.

**Comment by kotharironak** [comment]
I am thinking in the basic form it should take a time series as input and return baseline time series. There is some model that may need to calculate rate and so. For that, it will need a timestamp. So, instead of just giving input as a list of doubles, we should give time series which is a list of pairs [(timestamp, double)].

**Comment by rish691** [comment]
Some context around how alerting on baseline work as of today
Rule definition specifies the threshold type to be baseline and the baseline duration (duration of data to be used for baseline calculation). The evaluator fetches the metric data from pinot which is then used for both calculation of baseline and as lhs of the rule. Since rules are evaluated every minute the evaluation engine caches the metric data thus querying only a minutes data from pinot (in steady state).  Baseline is calculated using the formula [median +- stdev].

Since the baseline data shown in ui is served by gateway service, it is important to keep the method of baseline calculation consistent in the platform (cc @aaron-steinfeld )   ​

Summarising discussion with @kotharironak & @pavan-traceable 

There are mainly 3 ways in which alerting service can work with baseline:
1. A library of baseline utilities can be used by both gateway service and alerting service to compute baseline for the metric data 
2. Gateway service api which accept metric data, request params, it returns the computed baseline data 
3. Use existing gateway service baseline api, however the implementation fetches the complete set of metric data from pinot which could be a heavy operation. So an optimised version of the api can be used by alerting. 

Option [2] & [3] add an extra network call for the alerting service, which could potentially cause scale issues/sla breach for alerting
Option [3] adds to the pressure on pinot, as the number of periodic metric calls hitting it doubles, assuming all baseline rules 
(@laxmanchekka pointed out performance degradation of pinot for periodic queries)
In option [2], computation of baseline from metric data seems like a simple transformation and hitting a service over network seems like an overkill.  
[1] runs the problem of inconsistent lib version used by baseline/alerting, thus leading to inconsistency in baseline computations 

[1] ie. having a lib of baseline computation methods would anyways be useful for abstracting out baseline utilities and to start with alerting could leverage it as well

**Comment by kotharironak** [comment]
Both the approaches have their pros/cons as you pointed out. But, I think, all the additional transformations on raw metrics data, should happen in one place. (e.g both avg_rate and baseline calculation). And, that can be wrapped either in a library or inside a service.

However, as you and @pavan-traceable  suggested that for a service that the service should own the data and have a clear set of responsibilities, I am fine starting with the library and if required wrapping them in a separate service. Secondly, there are only two consumers as of now, so it will be easy to maintain. That way, we don't have two copies of the code.

**Comment by kotharironak** [comment]
@rish691 @sarthak77 if we are going with a library, where do you plan to keep this utility? I think we can keep it in `hypertrace-service` as it will be used in the query layer.
